import { PropRule } from "./types";

const TPT_50K_PHASES = [
  {
    id: "eval" as const,
    label: "Test (evaluation)",
    shortLabel: "TEST",
    profitTarget: 3000,
    passAt: 4000,
    passAtNote:
      "Official target $3,000, but request PRO only when best day < 50% of total profit. With ~$2k winners: total ≥ $4,000 (Updated Goal = Net P/L × 2). Never request at $3,001.",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD trailing — updates at ~5 PM ET on closing balance. Locks at starting balance ($50,000) once reached.",
    dailyLossLimit: null,
    evalConsistencyPct: 50,
    evalConsistencyNote:
      "Highest profit day ÷ Net P/L must stay below 50%. If breached, keep trading until total doubles (net × 2) — you have NOT failed, only delayed pass.",
    minTradingDays: 5,
    minTradingDaysNote: "5 separate calendar days with ≥1 trade each. Hitting target in 2 days still requires 3 more active days.",
    criticalWarnings: [
      "No daily loss limit — only the $2,000 trailing DD stops you.",
      "Consistency is checked at PRO upgrade request, not at $3,000 tick.",
      "PRB: use $300 risk until +$1,000 cushion, then $400.",
    ],
    notes: [
      "Monthly subscription during test (~$180/mo — verify current pricing).",
      "Scalping and automation allowed on test.",
      "News trading allowed on test (unlike PRO).",
    ],
    monthlyFee: 180,
    source: "takeprofittraderhelp.zendesk.com — Rule 5: Be Consistent",
  },
  {
    id: "funded" as const,
    label: "PRO (funded sim)",
    shortLabel: "PRO",
    trailingDD: 2000,
    ddMode: "intraday" as const,
    ddBehavior:
      "INTRADAY trailing from day one on PRO — follows peak balance in real time including unrealized P&L. Same $2,000 distance, much stricter than test EOD.",
    dailyLossLimit: null,
    payout: {
      profitSplit: "80/20 (you keep 80%)",
      bufferRequired: "$52,000 on $50K ($50,000 start + $2,000 max DD) — withdraw only profit above buffer",
      minPayoutUsd: undefined,
      maxPerPayout: "No published cap — daily requests allowed",
      frequency: "Daily (day-one eligible once above buffer)",
      payoutConsistency: "None on PRO",
      minDaysBeforeFirstPayout: "0 funded days — as soon as balance clears buffer",
      minWinningDays: "None",
      extras: [
        "Keep ≥1 round-trip trade per calendar week or account may be closed.",
        "News restriction: flat 1 minute before, during, and 1 minute after FOMC, NFP, CPI on PRO.",
        "Activation fee ~$130 (often discounted in promos).",
      ],
    },
    criticalWarnings: [
      "BIGGEST MECHANICAL CHANGE: EOD trail → intraday trail. 'Easy to pass, hard to keep' — keep BE at +1R.",
      "Do not withdraw until $52,000+ — buffer is start + max DD.",
      "Scale risk slowly on PRO; many blow in week one from intraday peak drawdown.",
    ],
    notes: [
      "PRO is still simulated; withdrawn profits are real.",
      "At $5,000 cumulative PRO profit you become eligible for PRO+ (opt-in via email).",
      "Recycle strategy: withdraw at $52k buffer and restart test before PRO+ — see strategies/strategy-dev/tpt-rules.md.",
    ],
    activationFee: 130,
    source: "takeprofittrader.com · TPT help center · fundedwiki.com (2026)",
  },
  {
    id: "funded_plus" as const,
    label: "PRO+ (upgraded funded)",
    shortLabel: "PRO+",
    trailingDD: 2000,
    ddMode: "intraday" as const,
    ddBehavior: "Same intraday $2,000 trail as PRO.",
    dailyLossLimit: null,
    payout: {
      profitSplit: "90/10 (you keep 90%)",
      bufferRequired: "None — withdraw from dollar one above prior balance",
      maxPerPayout: "No published cap — daily",
      frequency: "Daily",
      payoutConsistency: "None",
      minDaysBeforeFirstPayout: "0",
      minWinningDays: "None",
      extras: [
        "Unlock after $5,000 cumulative profit on PRO (email invitation; trader opts in).",
        "$5,000 frozen on PRO at upgrade; PRO+ starts at $0.",
        "Same weekly minimum-activity rule as PRO.",
      ],
    },
    criticalWarnings: ["We recycle before $5k PRO profit — avoid PRO+ unless economics change."],
    notes: ["Best long-term economics if you survive PRO intraday trail first."],
    source: "takeprofittrader.com PRO+ overview (2026)",
  },
];

const TOPSTEP_50K_PHASES = [
  {
    id: "eval" as const,
    label: "Trading Combine (evaluation)",
    shortLabel: "COMBINE",
    profitTarget: 3000,
    passAt: 3000,
    passAtNote:
      "Hit $3,000 profit target without breaching EOD MLL ($2,000 trail) or daily loss limit ($1,000). Also need 5 winning days (≥$150 net each). Combine consistency: best day must stay under 50% of profit target (<$1,500 on $50K) — MC approximates via best-day % of total at pass.",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior:
      "EOD trailing MLL $2,000 — floor ratchets up on end-of-day peaks only (not intraday). Locks at $50,000 starting balance once EOD balance reaches $52,000.",
    dailyLossLimit: 1000,
    evalConsistencyPct: 50,
    evalConsistencyNote:
      "Combine-only rule: largest single day must be < 50% of profit target ($1,500 on $50K), not 50% of cumulative profit. If breached, keep trading until best day falls below threshold vs expanded total.",
    minTradingDays: 5,
    minTradingDaysNote:
      "5 separate winning days with ≥$150 net profit each (calendar days, non-consecutive OK). DLL pauses the day — does not fail the Combine.",
    criticalWarnings: [
      "Only hard fail: EOD balance hits trailing MLL floor.",
      "Daily loss limit $1,000 flattens for the session — can still fail if close pushes you through MLL.",
      "Consistency is vs profit target ($1,500 cap), not vs total P/L like TPT.",
    ],
    notes: [
      "Standard path: $49/mo Combine + $149 activation after pass. No-Activation-Fee path: higher monthly, $0 activation.",
      "Max position: 5 minis / 50 micros on $50K.",
      "Simulated environment — not live capital until Live Funded call-up.",
    ],
    monthlyFee: 49,
    source: "topstep.com · tradecovex.com Combine rules (Apr 2026)",
  },
  {
    id: "funded" as const,
    label: "Express Funded Account (XFA — sim funded)",
    shortLabel: "XFA",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior:
      "EOD MLL same family as Combine. XFA balance starts at $0 at activation (Combine profit does not carry). Account may show negative balance down to -$2,000 before MLL lock at $0.",
    dailyLossLimit: 1000,
    payout: {
      profitSplit: "90/10 from dollar one (new traders from Jan 12, 2026; grandfathered: 100% first $10k lifetime then 90/10)",
      bufferRequired: "None — withdraw from positive balance once eligibility met",
      minPayoutUsd: 125,
      maxPerPayout:
        "50% of balance or per-payout cap — $50K new (post Apr 28, 2026): $2,000 Standard / $3,000 Consistency",
      frequency: "Standard: after 5 winning days ($150+). Repeat payouts: winning days + profitable since last payout.",
      payoutConsistency: "Standard path: none. Consistency XFA path: 40% best-day cap in payout window",
      minDaysBeforeFirstPayout: "Standard: 5 winning days ($150+ net). Consistency: 3 trading days + 40% consistency target",
      minWinningDays: "Standard: 5 days ≥$150 · Consistency: 3 days + largest day ≤40% of window profit",
      extras: [
        "Pick Standard OR Consistency path at activation — cannot switch mid-cycle.",
        "$149 activation on Standard Combine path; No-Activation-Fee Combine skips this.",
        "After each approved payout, balance is reduced by payout amount; MLL resets relative to new balance.",
        "Back2Funded reactivations follow same payout rules as original XFA.",
      ],
    },
    criticalWarnings: [
      "XFA rules ≠ Combine rules. Balance resets to $0 — rebuild profit on funded sim.",
      "Apr 2026 lowered $50K caps to $2k Standard / $3k Consistency on new No-Activation-Fee accounts.",
      "Vault MC models Standard path (no funded consistency cap).",
    ],
    notes: [
      "Still simulated — real payouts, not exchange live capital.",
      "~0.71% of XFA traders called to Live Funded (Topstep 2025 stats).",
    ],
    activationFee: 149,
    source: "marketing.topstep.com/express-funded-account-rules · tradecovex.com (Apr 2026)",
  },
  {
    id: "funded_plus" as const,
    label: "Live Funded Account (real capital)",
    shortLabel: "LIVE",
    trailingDD: 1000,
    ddMode: "eod" as const,
    ddBehavior:
      "Maximum Loss Limit — account must stay above $1,000 positive balance for remainder of Live account. Daily Loss Limit scales with unlocked available balance.",
    dailyLossLimit: null,
    payout: {
      profitSplit: "Per Live agreement — benchmark-day gated withdrawals",
      bufferRequired: "20% of combined XFA balance unlocked at start; +25% reserve increments via profit milestones",
      minPayoutUsd: undefined,
      maxPerPayout: "50% of your share of Trading Profits until 30 Benchmark Days; then 100%",
      frequency: "After 5 Benchmark Trading Days ($150+ profit) since Live effective date or last payout",
      payoutConsistency: "None — benchmark days and 50% cap until day 30",
      minDaysBeforeFirstPayout: "5 Benchmark Trading Days (Live only — XFA winning days do not count)",
      minWinningDays: "Benchmark day = trade + ≥$150 Trading Profits that day",
      extras: [
        "Call-up from XFA based on performance; one active Live account at a time.",
        "Live size = avg of paid-out XFA sizes, rounded up to $50K / $100K / $150K tier.",
        "Total lifetime payouts capped at 90% of Starting Balance + net Trading Profits (regulatory).",
        "Topstep Octagon: monthly performance bonuses separate from payouts.",
      ],
    },
    criticalWarnings: [
      "Real brokerage capital — not simulated. DLL shoulder-tap tightens risk in drawdown.",
      "Benchmark days reset product — Express winning days do NOT carry over.",
    ],
    notes: [
      "Balance expansion weekly (Fri close review, typically applied by Tuesday).",
      "Not modeled in vault MC — compare XFA (sim funded) for strategy testing.",
    ],
    source: "topstep.com/live-funded-account-rules (Jul 1, 2026)",
  },
];

const APEX_50K_EOD_PHASES = [
  {
    id: "eval" as const,
    label: "Evaluation (PA)",
    shortLabel: "EVAL",
    profitTarget: 3000,
    passAt: 3000,
    passAtNote: "No eval consistency rule. Pass at $3,000 within plan time limit.",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD trailing $2,000. Safety net locks trail at $52,100 on funded PA.",
    dailyLossLimit: 1000,
    evalConsistencyPct: 0,
    minTradingDays: 0,
    criticalWarnings: ["30 calendar day eval window on many plans — verify your subscription.", "DLL pauses day, does not auto-fail eval."],
    notes: ["Eval fee ~$197 + activation ~$99 (verify Rithmic/Tradovate bundle)."],
    evalFee: 197,
    activationFee: 99,
    source: "apextraderfunding.com (2026)",
  },
  {
    id: "funded" as const,
    label: "Performance Account (funded)",
    shortLabel: "PA",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD trail; safety net locks at $52,100 on $50K when reached.",
    dailyLossLimit: 1000,
    payout: {
      profitSplit: "90/10 typical on PA (verify plan)",
      bufferRequired: "Safety net / trailing threshold — profit above locked floor",
      minPayoutUsd: undefined,
      maxPerPayout: "Tiered by account — 8 trading days between payouts on many plans",
      frequency: "~8 trading days between payout requests (Apex typical)",
      payoutConsistency: "50% consistency on PA (Apex 4.0, Mar 2026)",
      minDaysBeforeFirstPayout: "8 trading days + minimum profit threshold",
      minWinningDays: "Varies by payout number (1st vs 5th payout)",
      extras: ["Payout rules change by payout count — read Apex dashboard for your PA.", "Contract limits scale with profit."],
    },
    criticalWarnings: ["Apex payout consistency is ON funded — unlike TPT PRO.", "MC in vault uses eval rules only for Apex."],
    notes: ["Consider EOD vs intraday plan choice at purchase — intraday is stricter."],
    source: "apextraderfunding.com payout policy (verify live)",
  },
];

const ALPHA_PREMIUM_PHASES = [
  {
    id: "eval" as const,
    label: "Premium evaluation",
    shortLabel: "EVAL",
    profitTarget: 3000,
    passAt: 4000,
    passAtNote: "50% eval consistency — same math as TPT: plan for ≥$4,000 if best day ~$2,000.",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD trailing $2,000.",
    evalConsistencyPct: 50,
    minTradingDays: 2,
    minTradingDaysNote: "Minimum 2 trading days on Premium eval.",
    criticalWarnings: ["Eval consistency 50% — distributed wins required."],
    notes: ["Monthly ~$79 on Premium eval."],
    monthlyFee: 79,
    activationFee: 149,
    source: "alpha-futures.com · help.alpha-futures.com",
  },
  {
    id: "funded" as const,
    label: "Premium funded",
    shortLabel: "FUNDED",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD MLL — verify funded dashboard.",
    payout: {
      profitSplit: "Verify plan (typically 80/90% tiered)",
      bufferRequired: "Verify Alpha funded docs",
      maxPerPayout: "Per Alpha payout schedule",
      frequency: "Per Alpha schedule",
      payoutConsistency: "None on Premium funded (eval consistency does NOT carry over)",
      minDaysBeforeFirstPayout: "Verify dashboard",
      minWinningDays: "Verify dashboard",
      extras: ["Premium funded: no consistency rule per Alpha docs — unlike eval."],
    },
    notes: ["Advanced plan has $4,000 target and tighter $1,750 MLL instead."],
    criticalWarnings: ["Confirm funded MLL and payout table on activation — Alpha updates plans."],
    source: "help.alpha-futures.com",
  },
];

const ALPHA_ZERO_PHASES = [
  {
    id: "eval" as const,
    label: "Zero evaluation",
    shortLabel: "EVAL",
    profitTarget: 3000,
    passAt: 3000,
    passAtNote: "No eval consistency — pass at $3,000 if DD and DLL respected.",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD $2,000 MLL.",
    dailyLossLimit: 1000,
    evalConsistencyPct: 0,
    minTradingDays: 2,
    criticalWarnings: ["Funded phase adds ~40% payout consistency — eval rule does NOT carry over."],
    notes: ["Monthly ~$77. No eval consistency on pass."],
    monthlyFee: 77,
    source: "alpha-futures.com",
  },
  {
    id: "funded" as const,
    label: "Zero funded",
    shortLabel: "FUNDED",
    trailingDD: 2000,
    ddMode: "eod" as const,
    ddBehavior: "EOD MLL.",
    dailyLossLimit: 1000,
    payout: {
      profitSplit: "Verify plan",
      bufferRequired: "Verify dashboard",
      maxPerPayout: "Per schedule",
      frequency: "Per schedule",
      payoutConsistency: "~40% on payout requests (Alpha Zero funded)",
      minDaysBeforeFirstPayout: "Verify dashboard",
      minWinningDays: "Verify dashboard",
      extras: ["Zero funded carries payout consistency even though eval had none."],
    },
    criticalWarnings: ["40% payout consistency on funded withdrawals."],
    notes: ["Log exact payout tier from Alpha dashboard when activated."],
    source: "alpha-futures.com",
  },
];

/**
 * Firm rules for $50K-class accounts (Jul 2026).
 * Top-level fields = eval summary for Monte Carlo. See `phases[]` for funded/payout detail.
 */
export const PROP_RULES: PropRule[] = [
  {
    id: "tpt50",
    firm: "Take Profit Trader",
    name: "TPT $50K Test → PRO",
    size: 50000,
    profitTarget: 3000,
    passAt: 4000,
    passAtNote: TPT_50K_PHASES[0].passAtNote!,
    trailingDD: 2000,
    ddMode: "eod",
    consistencyPct: 50,
    minDays: 5,
    evalFee: 170,
    monthlyFee: 180,
    activationFee: 130,
    source: "takeprofittrader.com · Zendesk Rule 5 · PRB_Trade_Checklist.md",
    verified: true,
    lastReviewed: "2026-07-14",
    phases: TPT_50K_PHASES,
  },
  {
    id: "topstep50",
    firm: "Topstep",
    name: "Topstep $50K (Combine → XFA)",
    size: 50000,
    profitTarget: 3000,
    passAt: 3000,
    passAtNote: TOPSTEP_50K_PHASES[0].passAtNote!,
    trailingDD: 2000,
    ddMode: "eod",
    dailyLossLimit: 1000,
    consistencyPct: 50,
    minDays: 5,
    monthlyFee: 49,
    activationFee: 149,
    source: "topstep.com · tradecovex.com (Apr 2026)",
    verified: true,
    lastReviewed: "2026-07-14",
    phases: TOPSTEP_50K_PHASES,
  },
  {
    id: "apex50-eod",
    firm: "Apex Trader Funding",
    name: "Apex $50K EOD Trail",
    size: 50000,
    profitTarget: 3000,
    passAt: 3000,
    passAtNote: APEX_50K_EOD_PHASES[0].passAtNote!,
    trailingDD: 2000,
    ddMode: "eod",
    dailyLossLimit: 1000,
    consistencyPct: 0,
    minDays: 0,
    evalFee: 197,
    activationFee: 99,
    source: "apextraderfunding.com",
    verified: true,
    lastReviewed: "2026-07-13",
    phases: APEX_50K_EOD_PHASES,
  },
  {
    id: "apex50-intraday",
    firm: "Apex Trader Funding",
    name: "Apex $50K Intraday Trail",
    size: 50000,
    profitTarget: 3000,
    passAt: 3000,
    passAtNote: "Intraday trail — stricter than EOD. MC understates bust risk.",
    trailingDD: 2500,
    ddMode: "intraday",
    consistencyPct: 0,
    minDays: 0,
    evalFee: 131,
    activationFee: 79,
    source: "apextraderfunding.com",
    verified: true,
    lastReviewed: "2026-07-13",
    phases: [
      {
        ...APEX_50K_EOD_PHASES[0],
        ddMode: "intraday",
        trailingDD: 2500,
        ddBehavior: "Intraday trailing — trails peak including unrealized P&L.",
        criticalWarnings: ["Intraday DD from eval — vault MC does not fully model this."],
      },
      { ...APEX_50K_EOD_PHASES[1], ddMode: "intraday", trailingDD: 2500 },
    ],
  },
  {
    id: "alpha-premium-50",
    firm: "Alpha Futures",
    name: "Alpha Premium $50K Eval",
    size: 50000,
    profitTarget: 3000,
    passAt: 4000,
    passAtNote: ALPHA_PREMIUM_PHASES[0].passAtNote!,
    trailingDD: 2000,
    ddMode: "eod",
    consistencyPct: 50,
    minDays: 2,
    monthlyFee: 79,
    activationFee: 149,
    source: "alpha-futures.com",
    verified: true,
    lastReviewed: "2026-07-13",
    phases: ALPHA_PREMIUM_PHASES,
  },
  {
    id: "alpha-advanced-50",
    firm: "Alpha Futures",
    name: "Alpha Advanced $50K Eval",
    size: 50000,
    profitTarget: 4000,
    passAt: 4000,
    passAtNote: "Higher target + tighter MLL $1,750. Eval consistency ~40–50%.",
    trailingDD: 1750,
    ddMode: "eod",
    consistencyPct: 40,
    minDays: 2,
    monthlyFee: 139,
    activationFee: 149,
    source: "help.alpha-futures.com",
    verified: true,
    lastReviewed: "2026-07-13",
    phases: [
      {
        id: "eval",
        label: "Advanced evaluation",
        shortLabel: "EVAL",
        profitTarget: 4000,
        passAt: 4000,
        trailingDD: 1750,
        ddMode: "eod",
        ddBehavior: "EOD $1,750 MLL — tighter than Premium.",
        evalConsistencyPct: 40,
        minTradingDays: 2,
        criticalWarnings: ["Tighter DD + higher target — slower but stricter pass."],
        notes: ["Funded rules: verify Alpha Advanced funded docs separately."],
        source: "help.alpha-futures.com",
      },
      {
        id: "funded",
        label: "Advanced funded",
        shortLabel: "FUNDED",
        trailingDD: 1750,
        ddMode: "eod",
        ddBehavior: "EOD $1,750 MLL on funded.",
        payout: {
          profitSplit: "Verify plan",
          bufferRequired: "Verify dashboard",
          maxPerPayout: "Per schedule",
          frequency: "Per schedule",
          payoutConsistency: "Verify — may differ from Premium",
          minDaysBeforeFirstPayout: "Verify",
          minWinningDays: "Verify",
          extras: [],
        },
        notes: ["Log exact funded rules from your Alpha dashboard when activated."],
        criticalWarnings: [],
        source: "help.alpha-futures.com",
      },
    ],
  },
  {
    id: "alpha-zero-50",
    firm: "Alpha Futures",
    name: "Alpha Zero $50K Eval",
    size: 50000,
    profitTarget: 3000,
    passAt: 3000,
    passAtNote: ALPHA_ZERO_PHASES[0].passAtNote!,
    trailingDD: 2000,
    ddMode: "eod",
    dailyLossLimit: 1000,
    consistencyPct: 0,
    minDays: 2,
    monthlyFee: 77,
    source: "alpha-futures.com",
    verified: true,
    lastReviewed: "2026-07-13",
    phases: ALPHA_ZERO_PHASES,
  },
];

export function ruleById(id: string): PropRule | undefined {
  return PROP_RULES.find((r) => r.id === id);
}

export function rulesByFirm(firm: string): PropRule[] {
  return PROP_RULES.filter((r) => r.firm === firm);
}

export function phaseById(rule: PropRule, phaseId: string) {
  return rule.phases.find((p) => p.id === phaseId);
}
